apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: jasonkeene/k8s-basics-talk-app
